#!/usr/bin/expect -f
set timeout 10
set ip "149.50.151.121"
set user "root"
set password "disgraF1.insumos"
set port "5023"

spawn ssh -o StrictHostKeyChecking=no -p $port $user@$ip
expect {
    -nocase "assword:" {
        send "$password\r"
        expect "#"
        send "journalctl -u disgraf-hub -n 200 --no-pager | grep -i 'Error AI'\r"
        expect "#"
        send "exit\r"
    }
}
expect eof
